# Generated by Django 6.0.3 on 2026-03-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('join_date', models.DateField()),
                ('duration_months', models.IntegerField(default=1)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('membership_type', models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium')], max_length=10)),
                ('status', models.CharField(default='Active', max_length=10)),
            ],
        ),
    ]
