# Generated by Django 6.0.3 on 2026-03-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_member_join_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-join_date']},
        ),
        migrations.AlterField(
            model_name='member',
            name='duration_months',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Suspended', 'Suspended')], default='Active', max_length=10),
        ),
    ]
